### ISSUE TITLE
Laravel5.5 composer update error

### ISSUE THREAD

**Issue by ichenhua** [kylekatarnls/laravel-carbon-2#3]
when run `composer update` in Laravel5.5，It throw this error:

```
Fatal error: Uncaught Error: Class 'UpdateHelper\UpdateHelper' not found in D:\wwwserver\me\81f7\vendor\kylekatarnls\update-helper\src\UpdateHelper\ComposerPlugin.php:31
Stack trace:
#0 [internal function]: UpdateHelper\ComposerPlugin->onAutoloadDump(Object(Composer\Script\Event))
#1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Script\Event))
#2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Sc
ript\Event))
#3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Autoload/AutoloadGenerator.php(312): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-autoload-d..
.', true, Array, Array)
#4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php(304): Composer\Autoload\AutoloadGenerator->dump(Object(Composer\Config), Object(Composer\Repositor
y\Insta in D:\wwwserver\me\81f7\vendor\kylekatarnls\update-helper\src\UpdateHelper\ComposerPlugin.php on line 31
```

**Comment by kylekatarnls** [comment]
Hi, could you try to remove the vendor directory, run `composer clear-cache` then `composer update` again?

**Comment by kylekatarnls** [comment]
I released a new version of the update that will check UpdateHelper\UpdateHelper exists before calling it, so if for any reason it's missing (installation corrupted for example), it will just skip the step, so it will not prevent composer command to end.
